version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: mud_postgres
    environment:
      POSTGRES_USER: muduser
      POSTGRES_PASSWORD: mudpass
      POSTGRES_DB: mud
    volumes:
      - mud_pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

volumes:
  mud_pg_data:
